### PR TITLE
Update manager.yaml

### PR DESCRIPTION
**Pull request by albertogeniola**
Upgrade resource limits to fix issue #52

### CODE REVIEW

**Comment by jakexks** [comment]
Thanks for your contribution! The tests are failing for an unrelated reason so I will fix them and merge it.

**Comment by albertogeniola** [comment]
Great to hear that. Keep up the great work!

**Comment by albertogeniola** [comment]
Hi! Any news on this matter?

**Comment by nasirhm** [comment]
I am facing the same issue, can we please have it merged.

**Comment by mattbates** [comment]
@jakexks wdyt?

**Comment by maelvls** [comment]
CI seems broken due to a breaking change in the https://go.kubebuilder.io/releases URL: https://github.com/kubernetes-sigs/kubebuilder/issues/2311. Another issue was that the kubebuilder envtest assets (apiserver, etcd) were moved out from the kubebuilder release tarball (which is not a tarball anymore; it's a plain binary now). Finding where to download the envtest deps is painful, but this PR helped: https://github.com/kubernetes-sigs/controller-runtime/issues/1657

**Comment by maelvls** [comment]
@jakexks I think the GitHub secret `AGE_SECRET_KEY` does not work in forks.

**Comment by maelvls** [comment]
Since the CI works on `main` and that the issue is that GitHub secrets aren't loaded for forks (cf [docs](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)), I will manually merge this PR.

We shall find a solution for this though 😅

**Pull request merged**
