### PR TITLE
Set helm chart version to v0.7.0 ready for release

### PR DESCRIPTION
**Pull request by MaesterZ**
Follow-up of https://github.com/jetstack/google-cas-issuer/pull/96 and https://github.com/jetstack/google-cas-issuer/pull/110 @SgtCoDFish

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
@MaesterZ Appreciate this! I've actually already done the release - https://github.com/jetstack/google-cas-issuer/releases/tag/v0.7.1

When a tag is pushed, the version is overridden and so we don't actually need to bump the versions in this chart. I hadn't realised that!

I'll close this as the release is done 😁  Thanks very much for your contribution!

**Comment by milesarmstrong** [comment]
@SgtCoDFish 👋 Hiya

Sorry to resurrect this thread / PR, however I don't think the chart has been released to https://charts.jetstack.io/, the latest version I see available is v0.6.2!

**Comment by SgtCoDFish** [comment]
Hey, thanks for raising that! You're correct, I can't see the newer versions on there. Weird, I'd figured that was covered by the automation. I'll take a look 👀

**Comment by SgtCoDFish** [comment]
OK, the charts should now be released and available! Thanks for the heads up, I hadn't realised the automation didn't cover that!

**Comment by milesarmstrong** [comment]
Thanks very much for the release!

**Pull request closed without merging**
