### PR TITLE
Add very useful values common with the main Cert-manager chart

### PR DESCRIPTION
**Pull request by MaesterZ**
New values like in https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

* commonLabels
* deploymentAnnotations
* podAnnotations
* podLabels
* nodeSelector
* affinity
* tolerations
* priorityClassName

### CODE REVIEW

**Comment by MaesterZ** [comment]
Should we bump the chart API version?
```
[ERROR] Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'
```

**Comment by mgoodness** [comment]
> Should we bump the chart API version?
> 
> ```
> [ERROR] Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'
> ```

Yes. Helm v2 (apiVersion :v1) was deprecated in November 2020.

**Comment by MaesterZ** [comment]
Done

**Comment by MaesterZ** [comment]
Not sure why exactly the CI is failing @irbekrm, not related to my changes:
> Error: google-github-actions/auth failed with: retry function failed after 1 attempt: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job. This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork. For more information, please see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by irbekrm** [comment]
@MaesterZ I will take a look at what we can do to allow contributions, hopefully at some point this week.

Thank you for your PR.

**Comment by MaesterZ** [comment]
Do I have anything to fix here? It's google cloud authentication error.

**Comment by inteon** [comment]
> Do I have anything to fix here? It's a google cloud authentication error.

That is an old test, the required tests are passing.

**Comment by davidd-da** [comment]
Still looking to get this merge, not sure how can I help. We can also bump to `0.7.0` in a new helm chart release maybe.

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve

Thanks for this! ❤️ 

Sorry it's taken a while to get this reviewed and merged. I'll try to take a look into releasing a new version of this issuer either today or tomorrow so that these changes are released live 👍

**Comment by wallrj** [comment]
@MaesterZ I've been writing some documentation explaining why to set priorityClassName when deploying cert-manager and what the value should be. Please read and feedback if you have time:
 * https://github.com/cert-manager/website/pull/1444

**Pull request merged**
